### ISSUE TITLE
SFTPFileSystemProvider.keepAlive always throws exception

### ISSUE THREAD

**Issue by askask** [robtimus/sftp-fs#3]
The method `SFTPFileSystemProvider.keepAlive(FileSystem fs)` should only throw a `ProviderMismatchException` if the passed file system is not an `SFTPFileSystem`, but it does always throw one.

**Comment by robtimus** [comment]
I forgot a return statement. I've just fixed this in version 1.2.1, and added unit tests to make sure it works in all cases (SFTPFileSystem, other file system, null). This version should be available in Maven shortly.
